### ISSUE TITLE
In Rubinius, version 2.0.9 emits creatively.

### ISSUE THREAD

**Issue by mustmodify** [tenderlove/psych#216]
This behavior is present in rbx 2.2 and 2.4 but not 2.1.

psych 2.0.8
---------------
    rbx-2.4.1 :001 > require 'yaml'
    rbx-2.4.1 :002 > Psych.dump({fu: 'bar'})
    => "---\n:fu: bar\n"
 
psych 2.0.9
------------------

    rbx-2.4.1 :001 > require 'yaml'
    rbx-2.4.1 :005 > Psych.dump({fu: 'bar'})
    => "--- !ruby/hash-with-ivars\nelements:\n  :fu: bar\nivars:\n  :@entries: !ruby/object:Rubinius::Tuple {}\n  :@capacity: 16\n  :@size: 1\n  :@max_entries: 12\n  :@state: &1 !ruby/object:Hash::State\n    compare_by_identity: false\n    head: &2 !ruby/object:Hash::Bucket\n      key_hash: 2112643688174279348\n      value: bar\n      link: \n      state: *1\n      key: :fu\n    tail: *2\n  :@mask: 15\n"

References
http://stackoverflow.com/questions/27949877/why-cant-bundle-find-gems-in-production-after-bundle-deployment
https://github.com/rubinius/rubinius/issues/3284

**Comment by jemc** [comment]
Rubinius uses instance variables in core classes like Hash, as they are implemented in Ruby.  Psych is incorrectly assuming here that any instance variables it finds in a Hash are "extra" instead of part of the language implementation.

**Comment by mustmodify** [comment]
https://github.com/tenderlove/psych/blob/47adf879591570daebde62895b3712c216710661/lib/psych/visitors/yaml_tree.rb#L370

**Comment by jemc** [comment]
Looks like this change was made to address this feature request: https://github.com/tenderlove/psych/issues/43

**Comment by tenderlove** [comment]
> Psych is incorrectly assuming here that any instance variables it finds in a Hash are "extra" (and must be serialized) instead of part of the language implementation.

How do I tell the difference between an ivar that a user set, and one that is specific to the implementation?  Should `instance_variables` be returning implementation specific data?

**Comment by sodabrew** [comment]
Interesting, this is analogous to the issue I have in rubinius/rubinius#3268.

**Comment by headius** [comment]
Seems like Hash in Rubinius needs to hide its instance vars, similar to Array and String:

```
~/projects/jruby $ rvm rbx-2.2.10 do ruby -e "p 'foo'.instance_variables"
[]

~/projects/jruby $ rvm rbx-2.2.10 do ruby -e "p [1,2].instance_variables"
[]

~/projects/jruby $ rvm rbx-2.2.10 do ruby -e "p({a:1,b:2}.instance_variables)"
[:@mask, :@size, :@capacity, :@max_entries, :@entries, :@state]
```

**Comment by jemc** [comment]
@tenderlove 

> How do I tell the difference between an ivar that a user set, and one that is specific to the implementation?

That's a good question; I don't know a good answer for you on this one.  You could compare to the instance variables in an "fresh" Hash like `{}` to get a baseline and subtract those, and this may work in the case of Rubinius' implementation, but in the general case you don't necessarily know that more instance variables won't show up later as side effects of method calls, or of the implementation changing its strategy.

> Should instance_variables be returning implementation specific data?

Maybe @brixen should weigh in here, but my initial answer is yes - that's what instance variables without accessors always are - implementation-specific.  I think that using `instance_variables` or `instance_variable_get` is always bound to reach deeper than the specified/guaranteed API surface of whatever object you're dealing with.

My question would be, is there a better way to make the OP in https://github.com/tenderlove/psych/issues/43 happy?  Especially considering their issue is with instance of *subclasses* of Hash rather than instances of Hash itself.  I don't see a valid use case for wanting to inject arbitrary instance variables into an *instance of Hash* (not a subclass) and expect them to be correctly serialized/deserialized in YAML - the imaginary user here should just add key/value pairs instead.  So, the change could be amended to apply to Hash subclasses instaead of Hash itself.  Or to give them a way to specify their own serialization/deserialization scheme without 'monkey patching' psych.
>

**Comment by jemc** [comment]
To be honest, serializing/deserializing arbitrary objects without a user-specified strategy in YAML seems like a fool's errand to me (just importing/exporting instance variables isn't guaranteed to get this right), but I have no problem if other users want to do this as long as it doesn't infringe on the basic YAML use case of dumping and parsing assemblies of primitives.

**Comment by headius** [comment]
Instance variables *have* been injected into core types before...for example, Rails added timezone information to Time so it would marshal.

I'm confused why Array and String don't report their instance vars in `.instance_variables`, though...why can't Rubinius's Hash do that?

**Comment by jemc** [comment]
@headius 
I think we all know that just because something is reachable in Ruby doesn't make it part of the object's API surface.

> Instance variables have been injected into core types before...for example, Rails added timezone information to Time so it would marshal.

Sure, instance variables can be injected into core types as much as you like.  But injecting them into *YAML primitive* types like string and array and expecting them to be serialized into the resulting YAML raises my eyebrow.

> I'm confused why Array and String don't report their instance vars in .instance_variables, though...why can't Rubinius's Hash do that?

I'm also confused about the same point - but my second question would be the opposite - why do these have to hide their instance variables?

**Comment by mustmodify** [comment]
I'm wondering whether automagically exposing instance variables on a hash follows the PoLS? I read the ticket #43 and, with respect

* This seems like a meta-meta edge case whose solution broke the most basic case. As such, perhaps it should be reconsidered?
* It isn't clear to me that YAML has the obligation to also act as Marshal at the expense of readability unless it's behind some kind of flag. example: Psych.dump(whatever, :unreadable => true)
* Would it be better to have the OP [write his own encode_with method](https://gist.github.com/mustmodify/b2e19e3470b93021ddb0)?

**Comment by headius** [comment]
>I'm also confused about the same point - but my second question would be the opposite - why do these have to hide their instance variables?

Because instance variables are not hidden in Ruby. If they can be introspected, they should be considered part of the object's state that *must* be serialized. Are you saying that Psych should have special-case logic just for Rubinius because it exposes hidden state for Hash but hides it for Array and String?

**Comment by jemc** [comment]
@headius 

> Because instance variables are not hidden in Ruby. If they can be introspected, ...

Again, just because you can reach some part of an object in Ruby doesn't mean it's part of the object's API.  I know you know this.  You could argue here that the ruby core classes are a special case, compared to classes defined in a gem, but I would disagree with that premise as well.

>  [instance variables] should be considered part of the object's state that must be serialized.

It's easy to find cases where the instance variables don't tell whole story, or where the values of instance variables are simply **unserializable** by Ruby introspection.  In fact, you're advocating hiding instance variables here because there is a **better strategy**  for serializing this kind of object than just copying its instance variables - namely, using the API surface of the object to get its keys and values and copy those.

> Are you saying that Psych should have special-case logic just for Rubinius because it exposes hidden state for Hash but hides it for Array and String?

No, I'm suggesting psych should treat Ruby classes that correspond to YAML primtiives as *primitive*, using the appropriate serialization mechanism.  If someone really needs this feature for types like `String` and `Array` and `Hash` (and I think this is pretty darn rare), I'd suggest some kind of opt-in flag on Psych.dump as @mustmodify suggested.

On the other hand, maybe it wouldn't be unprecedented or unreasonable for psych to add code to cater to a specific implementation: https://github.com/tenderlove/psych/pull/148

**Comment by tenderlove** [comment]
idk, if rbx knows how to hide internal ivars for String and Array, then this seems like an rbx bug.

> It isn't clear to me that YAML has the obligation to also act as Marshal at the expense of readability unless it's behind some kind of flag. example: Psych.dump(whatever, :unreadable => true)

My expectation of this library is to be as similar to Marshal as possible.  Array and String already had ivar dump support, the patch for #43 fixes the bug (missing support) for hashes.

I'd rather figure out why rbx behaves differently wrt the `instance_variables` method between String, Array, and Hash before doing anything with this ticket.

> On the other hand, maybe it wouldn't be unprecedented or unreasonable for psych to add code to cater to a specific implementation:

If added Rubinius specific code is the way to fix it, I will accommodate.  But we should figure out why `Array`, and `String` behave in one way, and `Hash` doesn't.

**Comment by headius** [comment]
#148 adds an identical port of the C logic to Java. It does not introduce special-case behavior. It would be necessary for any JVM-based Ruby to use Psych.

**Comment by jemc** [comment]
@tenderlove 
> I'd rather figure out why rbx behaves differently wrt the instance_variables method between String, Array, and Hash before doing anything with this ticket. [...] But we should figure out why Array, and String behave in one way, and Hash doesn't.

I agree, the difference between Array and Hash here violates the principle of least surprise - my guess is it was introduced as a workaround to a problem like this.  However, it is a slippery slope and I'd advocate it be reversed and we work to fix any widespread code (like psych) that assumes Arrays and Strings have an "empty" implementation.

> Array and String already had ivar dump support, the patch for #43 fixes the bug (missing support) for hashes.

Your desire for consistency here is totally reasonable.  I just want to re-evaluate whether things like this should be the default behavior:

```ruby
require 'psych'; Psych.dump("foo".tap { |s| s.instance_variable_set(:@bar, 88) })
#=> "--- !ruby/string\nstr: foo\nbar: 88\n"
```

Especially when,

```ruby
require 'psych'; Psych.dump("foo".tap { |s| s.instance_variable_set(:@str, 88) })
#=> "--- !ruby/string\nstr: foo\nstr: 88\n"
```

I think this use case is best served by an opt-in flag for users who know of and desire this behavior.

**Comment by jemc** [comment]
> #148 adds an identical port of the C logic to Java. It does not introduce special-case behavior. It would be necessary for any JVM-based Ruby to use Psych.

Unless JRuby provided a C APi.  If I'm not mistaken, Truffle is aiming to do this?

**Comment by headius** [comment]
Or Psych could be written in Ruby and not have native dependencies. In any case, this is irrelevant. What language the extension is written in has no bearing on the public capabilities and behavior of the library. The ext for MRI just happens to be in C, and the one for JRuby happens to be in Java. They behave the same.

**Comment by YorickPeterse** [comment]
The reasoning for Rubinius not hiding instance variables of Hash is because Hash is implemented completely in Ruby itself (https://github.com/rubinius/rubinius/blob/master/kernel/common/hash.rb / https://github.com/rubinius/rubinius/blob/master/kernel/common/hash_hamt.rb) whereas String/Array are partially in C++ (and hide some of their internals in said language).

Besides that I don't think we make any specific guarantees about _always_ hiding instance variables from core classes. Especially if we use Ruby for them (gasp) there's no way to hide them without introducing extra APIs for this.

**Comment by YorickPeterse** [comment]
To put some context behind this problem, this change breaks Bundler on Rubinius (https://github.com/rubinius/rubinius/issues/3284). Bundler seems to use YAML for _outputting_ settings in `.bundle/config` but in turn parses this file using `String#scan` and a regexp (at least if I'm right in thinking that https://github.com/bundler/bundler/blob/a2343c9eabf5403d8ffcbca4dea33d18a60fc157/lib/bundler/settings.rb#L158 is used for this). This now breaks because the file is no longer a collection of `key: value` lines.

**Comment by mustmodify** [comment]
I'm trying to figure out which of these is the correct question:

* Are people who write classes and use instance variable obligated to hide them if they don't want them serialized? If so, is there a Ruby way to do this other than `def instance_variables; []; end`"?
* are instance variables actually a surface api? (because my perception had been that message are the API and instance variables must be specifically exposed)
* Is it good to be consistent when not doing so is pretty reasonable and doesn't break people?

Given that the goal of this gem is to marshal classes whenever possible, if you can assist me in writing an encode_with method that just faithfully spits out the hash then we can just agree to disagree. My question is whether there is already a method for detecting whether the value should be further encoded or just spit out? 

    class Hash
       def encode_with(coder)
         self.each do |n,v|
          coder[n] = v
        end
      end
    end

**Comment by mustmodify** [comment]
Given that the goal of this gem is to marshal classes whenever possible, if you can assist me in writing an encode_with method that just faithfully spits out the hash then we can just agree to disagree. My question is whether there is already a method for detecting whether the value should be further encoded or just spit out? 

    class Hash
       def encode_with(coder)
         self.each do |n,v|
          coder[n] = v
        end
      end
    end

**Comment by jemc** [comment]
@mustmodify 
Well, if we're saying instance variables must be uniform between implementations of Ruby (and I'm not saying this), surely adding the method `Hash#encode_with` to Rubinius would be a violation of that same uniformity?

**Comment by headius** [comment]
I think the primary question boils down to this: should instance variables on core Ruby/YAML types be persisted into the YAML dump.

If the answer is yes, then the behavior as it exists now is correct and Rubinius would need to take steps to hide Hash state. If the answer is no, then none of the core types known to YAML (strings, lists, maps) should expose Ruby-specific state in YAML.

I don't have a strong opinion either way. Obviously it's going to require someone to make an exception, either in Psych by special-casing instance var handling for some core types, or in Rubinius to hide state that should never be used (persisted, modified) by someone outside the class. Right?

**Comment by brixen** [comment]
There are two conflated issues here:
1. Whether Rubinius should be free to implement Ruby classes as Ruby classes.
2. What the representation of Hash should be in YAML

Rubinius implements Ruby classes as Ruby classes. A Ruby class may or may not have instance variables. Whether String has instance variables has no bearing on whether Hash has instance variables. I will not make any compromises on this aspect.

The vast, vast majority of YAML I've seen in applications is a human-readable representation of Hashes and Arrays of simple values (eg numbers, Symbols, Strings). People *do not* expect their Hash instances to suddenly start showing up as `!ruby/hash-with-ivars`.

Psych should preserve the establish representation of Hash instances (regardless of whether it's a happenstance of MRI's C implementation of Hash) and provide a mechanism for people to request these "object" representations (with possible attendant security issues) if they chose to, but it should not be the default.

There is no Ruby mechanism for "hiding" instance variables. So, either Psych can 1) use the simple representation for Hash instances or 2) give Rubinius an API to do so or 3) include Rubinius specific code.

Until this is decided, I'm going to bundle a modified version of 2.0.9 / whatever-is-current and disallow loading anything else since the severity of this breakage is so high for users.

**Comment by jemc** [comment]
I've raised issue #217 with a clearer proposal that we can discuss there.
Resolving issue #217 would resolve this issue.

**Comment by headius** [comment]
@brixen Nobody suggested that Rubinius shouldn't implement Ruby core classes in Ruby. At issue is whether the Ruby-visible state inside those implementations should be serializing to YAML.

Whether people agree with the automatic serialization of instance vars is irrelevant; Psych (and Syck before it) have *always* automatically marshalled instance variables for user-defined classes. Recent changes, as in #43, expand that behavior to some core types. This is actually *more* consistent behavior as far as Ruby-land goes, since an object with instance vars is treated like an object with instance vars (for purposes of serialization), regardless of whether it's a "core" type or not.

That said, I agree with @jemc in #217: the core "atoms" of YAML should probably be considered sacred. It makes the behavior of marshaling core types less consistent (since they and only they will omit instance variables) but it fits the expectations of YAML consumers.

So, summary:

_If a core Ruby type is intended to serialize as a core, structural element in YAML, it should only serialize state appropriate to that structural element._

That covers strings, lists (Array), and maps (Hash) at least, and omits MyHashSubclass and friends because they are NOT core types and they have NEVER serialized as core structural elements.

I'm not sure what to do about the case of MyHashSubclass < Hash when the Hash impl has instance vars, though. Making Hash sacred solves the current issue but still leaves a narrower one behind.

**Comment by jemc** [comment]
@headius 
I agree with your solution, and am working on a PR for it (as mentioned in issue #217).

> I'm not sure what to do about the case of MyHashSubclass < Hash when the Hash impl has instance vars, though. Making Hash sacred solves the current issue but still leaves a narrower one behind.

I think we'll just have to leave that one to fall through the cracks and say that that usage of a Hash isn't compatible with Rubinius + psych until we have some other way to deal with this.  If the OP of #43 is interested in using their code on Rubinius, we can try to work with them individually.  Implementing the proposed solution fixes the major, mission-critical cases that broke for the wide base of Rubinius users (bundler, etc...).

**Comment by headius** [comment]
>I think we'll just have to leave that one to fall through the cracks and say that that usage of a Hash isn't compatible with Rubinius + psych until we have some other way to deal with this.

Agreed. A possible solution has even been suggested: when Psych boots, it could get a list of instance vars from the core types in question and subtract those from the "extra" ones it serializes for subclass versions. Basically,
```ruby
# At boot:
HASH_IMPL_IVARS = {}.instance_variables;

# In the logic that persists and restores ivars to/from the YAML dump:
hash_sub_vars = hash_sub_obj.instance_variables - HASH_IMPL_IVARS
```

**Comment by headius** [comment]
I should also say that I find the `{}.instance_variables` fix to be pretty hacky. Unfortunately, I have been unable to think of a better way to automatically serialize *only* userland-defined instance vars.

**Comment by jemc** [comment]
@headius 

See my earlier comment:
> You could compare to the instance variables in an "fresh" Hash like `{}` to get a baseline and subtract those, and this may work in the case of Rubinius' implementation, but in the general case you don't necessarily know that more instance variables won't show up later as side effects of method calls, or of the implementation changing its strategy.

**Comment by headius** [comment]
@jemc That would be a problem, and it may be entirely incompatible with omitting impl-specific ivars in core classes. But it's a hypothetical case, since Rubinius does no such runtime analysis or strategy-picking right now. I believe it doesn't even use HAMT unless you specify it as a startup or compile flag, right? Better to not get bogged down in hypothetical scenarios.

**Comment by jemc** [comment]
@headius 

> But it's a hypothetical case, since Rubinius does no such runtime analysis or strategy-picking right now. I believe it doesn't even use HAMT unless you specify it as a startup or compile flag, right?

Correct, it's an `RBXOPT`.

> Better to not get bogged down in hypothetical scenarios.

Sure, although right now, someone needing to serialize/deserialize an instance of Hash with an extra ivar via psych is also hypothetical ;)

**Comment by headius** [comment]
@jemc I'm not arguing for non-subclassHash ivars to serialize either.

**Comment by jemc** [comment]
@headius Hence, the *wink* ;)

**Comment by headius** [comment]
@jemc Text is difficult, isn't it :-) Thanks for the patch. I have to shut down now but maybe you can file an issue for the remaining subclass ivar problems.
