### ISSUE TITLE
Invalid YAML generated? (!omap vs !!omap)

### ISSUE THREAD

**Issue by josephbisch** [tenderlove/psych#241]
My issue is described in [this SO question that I posted](http://stackoverflow.com/questions/31323105/yaml-generated-by-ruby-appears-invalid-omap-vs-omap).

Essentially it appears like Psych is emitting `!omap` instead of `!!omap` when generating YAML. This causes problems when trying to parse the resulting YAML using standards-compliant YAML parsers.

In particular, check out [this line in Psych](https://github.com/tenderlove/psych/blob/e1d7f705da01349b93420cd7f54576949d694a69/lib/psych/visitors/yaml_tree.rb#L159).

**Comment by tenderlove** [comment]
Ya, we should change this.  Emitting `!omap` is due to historical issues, specifically that's what Syck would emit (even though it's not correct).  It's still valid YAML, and you should be able to work around it by teaching your YAML parser that `!omap` is the same as `!!omap`.

If you send a PR, I'll merge it, or I'll fix this when I get some time.
